# Generated by Django 5.1.2 on 2024-10-20 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_alter_advertisement_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='avertisements',
            new_name='advertisements',
        ),
        migrations.AddConstraint(
            model_name='favorites',
            constraint=models.UniqueConstraint(models.F('users'), models.F('advertisements'), name='users-advertisements-unique-constraint'),
        ),
    ]
