# Generated by Django 5.1.2 on 2024-10-20 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_rename_avertisements_favorites_advertisements_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorites',
            name='users-advertisements-unique-constraint',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='advertisements',
            new_name='advertisement',
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='users',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='favorites',
            constraint=models.UniqueConstraint(models.F('user'), models.F('advertisement'), name='user-advertisement-unique-constraint'),
        ),
    ]
