# Generated by Django 5.1.2 on 2024-10-21 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_remove_favorites_users_advertisements_unique_constraint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='in_favorites',
            field=models.ManyToManyField(related_name='+', through='advertisements.Favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
